### ISSUE TITLE
Extension doesn't work of value host is not capitalized

### ISSUE THREAD

**Issue by fbartels** [brot/gnome-shell-extension-sshsearch#1]
Hi,

first of all thanks for this really helpful shell extension. I found two "problems", I will create another issue for the secound problem.

System: Ubuntu 11.10 64bit with gnome-shell 3.2.1-0ubuntu1 (from proposed), installed your extension from extension.gnome.org

If the the keyword "host" in .ssh/config begins with a small h, then the entry is not parsed and therefore doesnt show up in the search provider. Here an example:

host gnome-test
  User test
  Hostname test.tld

**Comment by brot** [comment]
Thank you for your report. Could you please test the latest version. I also uploaded the latest version to https://extensions.gnome.org, but this version had to be reviewed. So I'm not sure if you get the latest version when installing from the website.

Would be nice to know if the extension now works for you.

**Comment by fbartels** [comment]
Thanks. This issue is indeed fixed with a recent git checkout (not yet on extensions.gnome.org)
