### ISSUE TITLE
when several hostnames are defined, hostname is one string

### ISSUE THREAD

**Issue by fbartels** [brot/gnome-shell-extension-sshsearch#2]
Hi,

System: Ubuntu 11.10 64bit with gnome-shell 3.2.1-0ubuntu1 (from proposed), installed your extension from extension.gnome.org

When several hostnames are defined in a single rule, the search provider will take the whole name and wont recognize each hostname seperately:

Example

Host 192.168.11.11 192.168.11.13 192.168.11.15 192.168.11.16
  User root
  ProxyCommand ssh -q -a -x gateway nc %h 22

Trough the shell I can connect to each machine seperately via ssh 192.168.11.11, the search provider unfortunately gets "192.168.11.11 192.168.11.13 192.168.11.15 192.168.11.16" as a single machine.

**Comment by brot** [comment]
Thank you for your report. Could you please test the latest version. I also uploaded the latest version to https://extensions.gnome.org, but this version had to be reviewed. So I'm not sure if you get the latest version when installing from the website.

Would be nice to know if the extension now works for you.

**Comment by fbartels** [comment]
Thanks for your fast reply. This issue is also solved with the latest git checkout.
