### ISSUE TITLE
Doesn't look at /etc/ssh/ssh_known_hosts

### ISSUE THREAD

**Issue by argv-minus-one** [brot/gnome-shell-extension-sshsearch#5]
I often put a bunch of known hosts in `/etc/ssh/ssh_known_hosts`. It would be useful for the extension to look there as well. Note that some systems name this file `/etc/ssh_known_hosts` instead.

**Comment by brot** [comment]
New version is available through https://extensions.gnome.org/extension/73/ssh-search-provider/ now
