### ISSUE TITLE
Is it possible to search in the the `Alt+F2` run dialog?

### ISSUE THREAD

**Issue by daroczig** [brot/gnome-shell-extension-sshsearch#6]
Thanks for great extension!

As triggering the overview is quite slow, I was thinking if the search mechanism could be also used when pressing `Alt+F2` in gnome-shell to trigger the run dialog. So after pressing `Alt+F2` the run dialog shows up very quickly where I can start commands in my `$PATH`, but it would be cool if the hostnames would be found too.

This questions is rather a `gnome-shell` question I suppose, but I would be really thankful if anyone could point me to a good direction. Is it possible?

**Comment by brot** [comment]
I'm not aware of such a functionality. Because I use the searchprovider functionality of gnome-shell and so I think that this is not possible
