### ISSUE TITLE
Do not parse lines which are commented out (starting with `#`)

### ISSUE THREAD

**Issue by daroczig** [brot/gnome-shell-extension-sshsearch#7]
I have quite a few hosts commented out in my `~/ssh/config` file which are not needed most of the time. Once a year I enable those for a week or so.

Would it require much coding to skip the commented out lines in the `config` file? If so, I would keep this simple by removing those lines and keeping just in a backup dir, so pls feel free to close this, if you think this would not make much sense.

**Comment by brot** [comment]
I uploaded the fixed version to extensions.gnome.org. 
As soon as they approve my changes you can update your extension to the latest version and your configuration marked with a comment will be ignored in the search result.

**Comment by daroczig** [comment]
Awesome, thanks!

**Comment by brot** [comment]
The update should now be available on http://extensions.gnome.org/
