### ISSUE TITLE
only 1 line of results shown

### ISSUE THREAD

**Issue by nean-and-i** [brot/gnome-shell-extension-sshsearch#8]
I only get 1 line but I do have more results which didn't get viewed - is this limited by the extension or just a gnome setting somewhere?

**Comment by brot** [comment]
I looked at your report today and I fear I can't control the output of the search result. I'm only sending the result and Gnome shell handles the output.

It seems that this behaviour isn't unique to my SSHSearch provider, but also for the Application or other search providers. If I type "s" there is only one line for the application result. But there are surely more than this few applications with the search query "s"

I asked this question in the #gnome-shell irc channel and here is the question+answer:

```
23:04 < BerndSch_> Hi, I have a question regarding the search result in the shell. Why is there only 1 line of
                   the search result per provider? Is there a >> setting to increase to number of lines for an search
01:04 <@Jasper> BerndSch_, not yet, but there's a search rework in progress that will fix that
```

So you/we have to wait for the gnome guys to fix this issue. There is nothing I can do here at the moment.
