### ISSUE TITLE
Terminal profile per destination?

### ISSUE THREAD

**Issue by kaj** [brot/gnome-shell-extension-sshsearch#9]
Is there a way to select a terminal profile per destination?

I like to have one terminal profile for local and miscellaneous shell account terminals and another (visually different) profile for e.g. production web servers.  That helps me avoid doing stupid things on the wrong hosts ...  :-)

So either if gnome-term can be made to recognize the commands this extension uses and select different profiles by itself (maybe an existing feature in gnome-terminal that I just don't know about?) or if gnome-shell-extension-sshsearch can be made to tell the terminal what profile to use, maybe based on directives / comments in .ssh/config?

**Comment by brot** [comment]
Sorry for the late answer.

First I didn't find a way to define a terminal profile when starting the terminal with a command from the command line. Do you know a way?

Second I try to avoid to build a settings gui for the extension as long as possible. The extension should be as simple as possible. At least that is my opinion.

But if someone will develop your feature request I have no problem to include this change in this extension.

**Comment by RickyFletcher** [comment]
Hello,

There is a way to open a gnome-terminal with profile from command... 

gnome-terminal --profile=X

Maybe a way is to create profiles with the same name of the hostname and that could match the profile with all the options that you could customize from the gnome-terminal GUI.

What do you think?

regards..

RF

**Comment by RickyFletcher** [comment]
Hello kaj,

I just modified the script to add compatibility with profiles. I'm using TERMINAL_APP='terminator', and you need to modify the following lines.

BEFORE:

 if port == SSH_DEFAULT_PORT:
            # don't call with the port option, because the host definition
            # could be from the ~/.ssh/config file
            GLib.spawn_command_line_async('%s -e "ssh %s"' % (TERMINAL_APP, target))
        else:
            GLib.spawn_command_line_async('%s -e "ssh -p %s %s"' % (TERMINAL_APP, hoststring, port, target))

AFTER:

 if port == SSH_DEFAULT_PORT:
            # don't call with the port option, because the host definition
            # could be from the ~/.ssh/config file
            GLib.spawn_command_line_async('%s -p %s -e "ssh %s"' % (TERMINAL_APP, hoststring, target))
        else:
            GLib.spawn_command_line_async('%s -p %s -e "ssh -p %s %s"' % (TERMINAL_APP, hoststring, port, target))

Please, note that your profile name in terminator needs to match the hoststring var, which is the name of the server that the script will parse in the ~/.ssh/config... else, the terminator will use the default profile.

Hope this help.

Best regards

Ricky Fletcher
